name: Build and Deploy to Cloudflare KV

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.10

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the build script
      - name: Run build script
        run: python build.py

      # Upload to Cloudflare KV
      - name: Upload to Cloudflare KV
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_NAMESPACE_ID: ${{ secrets.CLOUDFLARE_NAMESPACE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          npm install -g wrangler
          cd output/_dnd5e
          for file in $(find . -type f); do
            key=$(echo "$file" | sed -e 's|^\./||' -e 's|\.[^.]*$||')
            wrangler kv:key put "$key" --path $file \
              --namespace-id $CLOUDFLARE_NAMESPACE_ID
          done
